// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8zHkT0Cn1M5v3oL0Fjwrk6dzYghmlE5c',
    appId: '1:806765012577:web:824cff51585f5b8477ac20',
    messagingSenderId: '806765012577',
    projectId: 'notetaking-4c225',
    authDomain: 'notetaking-4c225.firebaseapp.com',
    storageBucket: 'notetaking-4c225.firebasestorage.app',
    measurementId: 'G-D1B1LKMM52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbL9N2wZol6GxwBG7o67KRHe5khcM6NXo',
    appId: '1:806765012577:android:fbc381a3e72e595177ac20',
    messagingSenderId: '806765012577',
    projectId: 'notetaking-4c225',
    storageBucket: 'notetaking-4c225.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4VX9SIyDKJQGPLfMmd3HRr8IwgpM6F90',
    appId: '1:806765012577:ios:6dafbc9f10c3c9e277ac20',
    messagingSenderId: '806765012577',
    projectId: 'notetaking-4c225',
    storageBucket: 'notetaking-4c225.firebasestorage.app',
    androidClientId: '806765012577-hupd2bvenidln8tpp9o4ktjpdlamqu20.apps.googleusercontent.com',
    iosClientId: '806765012577-p4q2ev4qpnevoclf6qpbv4rfm41gvp3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4VX9SIyDKJQGPLfMmd3HRr8IwgpM6F90',
    appId: '1:806765012577:ios:6dafbc9f10c3c9e277ac20',
    messagingSenderId: '806765012577',
    projectId: 'notetaking-4c225',
    storageBucket: 'notetaking-4c225.firebasestorage.app',
    androidClientId: '806765012577-hupd2bvenidln8tpp9o4ktjpdlamqu20.apps.googleusercontent.com',
    iosClientId: '806765012577-p4q2ev4qpnevoclf6qpbv4rfm41gvp3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8zHkT0Cn1M5v3oL0Fjwrk6dzYghmlE5c',
    appId: '1:806765012577:web:33975abe1c5a15fb77ac20',
    messagingSenderId: '806765012577',
    projectId: 'notetaking-4c225',
    authDomain: 'notetaking-4c225.firebaseapp.com',
    storageBucket: 'notetaking-4c225.firebasestorage.app',
    measurementId: 'G-SJV94XM6DF',
  );
}
